MINIMUM_REGRESSION_TEST_TIMEOUT_SECONDS: float = 0.5
TIMEOUT_MULTIPLIER_FOR_REGRESSION_TEST: float = 10.0
TIMEOUT_MULTIPLIER_FOR_DIFFERENTIAL_TEST: float = 5
RANDOM_SQLS_GENERATION_TIMEOUT_SECONDS: float = 60
MINIMUM_DIFFERENTIAL_TEST_TIMEOUT_SECONDS: float = 2.0


